worker_processes 1;
worker_shutdown_timeout 5s;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    access_log /dev/stdout;
    error_log /dev/stderr warn;
    resolver @@RESOLVER@@ valid=10s;
    @@UPSTREAM@@
    server {
        listen 8080;
        root /usr/share/nginx/html;
        client_max_body_size 100M;
        location ~ ^/internal(/|$) { return 404; }
        location ~ ^/(api|health)(/|$) {
            @@PROXY@@
        }
        location / { try_files $uri $uri/ /index.html; }
    }
}
