events {
    worker_connections 1024;
}

http {
    resolver ${DNS_RESOLVER} valid=10s;

    upstream drive_backend {
        zone drive_backend 64k;
        # BACKEND_SERVERS
    }

    server {
        listen 8080;

        # Permite upload de arquivos maiores (ex: até 100MB)
        client_max_body_size 100M;

        location / {
            proxy_pass http://drive_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
            proxy_next_upstream_timeout 5s;
        }
    }
}
